#pragma once

#include "AssetCache.h"
#include "../../Renderer/Common/Shader.h"

#include <string>

namespace Rivet::Assets {

    // -------------------------------------------------------------------------
    // ShaderManager
    //
    // Wraps AssetCache<Shader>.  Shaders are compiled once and shared;
    // calling LoadShader with the same (vert, frag) pair returns the same
    // cached program handle.
    //
    // Cache key: "<vertPath>|<fragPath>"
    //
    // Call UnloadAllShaders() at shutdown to delete GPU programs.
    // -------------------------------------------------------------------------

    // Compile (or retrieve) a shader program from two GLSL source files.
    // Returns the cached OpenGL program handle (0 on compile/link failure).
    Shader LoadShader(const std::string& vertPath, const std::string& fragPath);

    // Return the cached shader for the given key, or 0 if not yet loaded.
    // The key must match the one auto-generated by LoadShader: "vert|frag".
    Shader GetShader(const std::string& vertPath, const std::string& fragPath);

    // Release all cached shaders and delete their GPU programs.
    void UnloadAllShaders();

} // namespace Rivet::Assets
